# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40ec03d90d4f11df5adff3aaaf9a4bc570483b11818fab45486ed46edcc0a73bddd83d15361f394d9e9495b3a3576c0dec0404e9f3d35a5e7337f67ea6d8d80

test:
  secret_key_base: 554e668141b88b3c925c0bc71b225b9c3e921d7878e647b935f18d236f406e4da583bfb5a77ac86712a8a70e593d093bbdc670aefb4191cfe32de1293bfeea0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
